# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ros < Formula
  desc "CLI tool for managing MikroTik RouterOS routers with structured JSON output"
  homepage "https://github.com/nic0der-im/routeros-cli"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.5.0/ros_0.5.0_darwin_amd64.tar.gz"
      sha256 "53b9a953a7c575492a3ee8fd59cc78893241ede9dcf8e28c4c6bdfea33fce74f"

      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.5.0/ros_0.5.0_darwin_arm64.tar.gz"
      sha256 "46c524a8973b9da7d2a57c62b5a761698824cdc628f0ed05a1d31d2ec870f1b8"

      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.5.0/ros_0.5.0_linux_amd64.tar.gz"
      sha256 "54e6a8e741d28eb8f57f443c7826a111be064e37ab97000ff3d2a49f7432e67f"
      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.5.0/ros_0.5.0_linux_arm64.tar.gz"
      sha256 "903fedd76555ff8d51e2711677e72ff33dcf2eb70fc655d9a96486e7057a1f8a"
      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
  end

  test do
    assert_match "ros", shell_output("#{bin}/ros version")
  end
end
