# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ros < Formula
  desc "CLI tool for managing MikroTik RouterOS routers with structured JSON output"
  homepage "https://github.com/nic0der-im/routeros-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.4.0/ros_0.4.0_darwin_amd64.tar.gz"
      sha256 "3b87961eb3d0d53059b5c23d727f7c7d7b150065833e4dcb2bc337fe72d3b05f"

      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.4.0/ros_0.4.0_darwin_arm64.tar.gz"
      sha256 "53a1ec04b461a430b19e657b2ae0e8cf784a857ecdb9ea1f46634f9753b76272"

      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.4.0/ros_0.4.0_linux_amd64.tar.gz"
      sha256 "ee6325e1012e4da76d182f6241b3b5a9985e394d17b2d005683bc961f3631e25"
      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.4.0/ros_0.4.0_linux_arm64.tar.gz"
      sha256 "7cf09ed8f491bb67101e686d3b884c0a73ab67781ebbdd0dff0d3c358e203b83"
      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
  end

  test do
    assert_match "ros", shell_output("#{bin}/ros version")
  end
end
