# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ros < Formula
  desc "CLI tool for managing MikroTik RouterOS routers with structured JSON output"
  homepage "https://github.com/nic0der-im/routeros-cli"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.3.3/ros_0.3.3_darwin_amd64.tar.gz"
      sha256 "2c343c08121b8d567c5ba2f7c1c7211ead475c0cf1d14aac0c3a39f091a9e56c"

      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.3.3/ros_0.3.3_darwin_arm64.tar.gz"
      sha256 "c88a48f6620d6fd8f2dc72d1042664bd7c9cf88489b593c84a2b6d01c4e8a21d"

      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.3.3/ros_0.3.3_linux_amd64.tar.gz"
      sha256 "7e6627c1423acb55aa06ccb734c31f12177c60a0141b4460e1a1153c3f832c75"
      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nic0der-im/routeros-cli/releases/download/v0.3.3/ros_0.3.3_linux_arm64.tar.gz"
      sha256 "776a3ecead840811033f90d4928f1f52abd804773610d0fb12ded95a6eb50270"
      define_method(:install) do
        bin.install "ros"
        bin.install_symlink "ros" => "routeros-cli"
        generate_completions_from_executable(bin/"ros", "completion")
      end
    end
  end

  test do
    assert_match "ros", shell_output("#{bin}/ros version")
  end
end
